show databases; -- get all the databases present in the shcemas
SELECT * FROM RGM;

UPDATE RGM SET NAME="PAVABI" WHERE CONTACT_NUMBER = 90144334; -- UPDATE THE EXISTING VALUE

UPDATE RGM SET SESSION = 'JAVA' , ADDRESS='KURNOOL' WHERE CONTACT_NUMBER = 9013335; -- UPDATING MULTIPLE VALUES

SELECT * FROM STUDENT;

SELECT * FROM RGM;
CREATE TABLE TEST(STUDENT_ID INT PRIMARY KEY ,STUDENT_NAME VARCHAR(30),STUDENT_CONTACT INT,STUDENT_DEPT VARCHAR(20));

SELECT * FROM TEST;

INSERT INTO TEST SELECT * FROM STUDENT; -- COPY STUDENT DATA INTO THE TEST TABLE

TRUNCATE TABLE TEST; -- DELETE DATA NOT TABLE STUCTURE

SELECT * FROM STUDENT;

DELETE FROM STUDENT WHERE STUDENT_NAME='PAVANI'; -- DELETE ENTIRE ROW

DROP TABLE TEST; -- DELETE THE TABLE

SELECT * FROM STUDENT;

ALTER TABLE STUDENT RENAME COLUMN STUDENT_NAME TO NAME; -- RENAME THE COLUMN NAME

ALTER TABLE STUDENT RENAME TO RGM_STUDENT; -- RENAME TABLE NAME

SELECT * FROM RGM_STUDENT;

CREATE DATABASE SUNS;

SHOW DATABASES;

DROP DATABASE SUNS; -- TO DROP THE DATABASE

ALTER TABLE RGM_STUDENT ADD ADDRESS VARCHAR(30); -- ADD COLUMN TO TABLE

UPDATE RGM_STUDENT SET ADDRESS = 'HYDERABAD' WHERE STUDENT_ID=40; -- ADD DATA TO NEW COLUMN

ALTER TABLE RGM_STUDENT MODIFY COLUMN ADDRESS VARCHAR(50); -- ALTER COLUMN DATATYPE OR SIZE

ALTER TABLE RGM_STUDENT DROP COLUMN ADDRESS; -- DROP PARTICULAR COLUMN
