show databases;-- get all the databases which are ptresent in the schema
SELECT *FROM students;
-- changing the values

UPDATE students SET Name="deepti" WHERE contact_number=5432563;

SELECT *FROM students;

UPDATE students SET session="java" , Address="atp" WHERE  contact_number=123;

CREATE TABLE TEST(STUDENT_ID INT PRIMARY KEY,STUDENT_NAME VARCHAR(50),STUDENT_CONTACT INT,STUDENT_DEPT VARCHAR(30));

SELECT *FROM TEST;

INSERT INTO TEST SELECT * FROM student;-- COPY THE STUDENT DATA INTO TABLE TEST

TRUNCATE TABLE student; -- delete the data not the structure

DELETE FROM student WHERE student_name="pavani";

DROP TABLE TEST; -- DELETE THE TABLE

SELECT *FROM student;

ALTER TABLE student RENAME COLUMN STUDENT_NAME  TO NAME;

ALTER TABLE STUDENT RENAME TO  RGM_STUDENT;-- TO CHANGE THE DATA

SELECT *FROM RGM_STUDENT;

CREATE DATABASE SUNS;

DROP DATABASE SUNS; -- DROP THE DATABASE

SHOW DATABASES;

SELECT *FROM RGM_STUDENT;

ALTER TABLE RGM_STUDENT ADD NAME VARCHAR(30);

UPDATE RGM_STUDENT SET NAME="PAVANI";

INSERT INTO RGM_STUDENT (NAME) VALUES("PAVANI")