CREATE TABLE PAVANI(ID INT ,FILED INT,MARKS INT);
TABLE PAVANI;
INSERT INTO PAVANI VALUES(1,1,1),(NULL,NULL,NULL),(1,NULL,NULL);
SELECT COUNT(*) FROM PAVANI;  -- IT WILL INCLUDE NULL AND DUPLICATES ALSO
SELECT COUNT(ID) FROM PAVANI; -- IT WILL DOESNOT INCLUDE NULL,AND ALLOW DUPLICATES
SELECT COUNT(DISTINCT ID) FROM PAVANI; -- IT WILL DOESN'T ALLOW NULL AND DUPLICATES