-- FIND ALL THE ROWS WHERE RSESSION IS EQUAL TO JAVA 
SELECT * FROM rgm WHERE RSESSION = "JAVA";

SELECT ID ,NAME_,RSESSION FROM rgm WHERE RSESSION = "JAVA";
SELECT * FROM rgm ;

SELECT * FROM rgm WHERE RSESSION = "MYSQL" AND ADDRESS = "KURNOOL";

SELECT * FROM rgm WHERE ADDRESS = "KURNOOL";

SELECT * FROM rgm WHERE NAME_ LIKE "S%";

SELECT * FROM rgm WHERE NAME_ LIKE "SA%";

SELECT * FROM rgm WHERE NAME_ LIKE "%A";

SELECT * FROM rgm WHERE NAME_ LIKE "_M%";

SELECT * FROM rgm WHERE NAME_ NOT LIKE "S%";

SELECT * FROM rgm WHERE NAME_ NOT LIKE "_M%";
